name: stacks-starterererer
description: This is a stack to create a stack.
branding:
  icon: layers
  color: blue

inputs:
  - name: DEV_SPN_ID
    description: SPN ID for Dev deployments
    is-secret: true

configs:
  # Meta data for creating the new repository
  repo-metadata:
    parameters:
      topics:
        - abc
      secrets: 
      - name: DEV_SPN_ID
        value: ${{inputs.DEV_SPN_ID}}
